import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(
    page_title="Molecular generator",
    page_icon="🕹",
)
st.sidebar.header("Molecular generators:")

web = True
if web == True:
    current_directory = '/mount/src'
else:
    current_directory = '/workspaces'

st.sidebar.markdown('**Molpher**')
st.sidebar.markdown('**DrugEx GT**')
st.sidebar.markdown('**DrugEx RNN**')
st.sidebar.markdown('**REINVENT**')
st.sidebar.markdown('**GB_GA**')
st.sidebar.markdown('**Add carbon**')
st.sidebar.markdown('**VAE generator**')

st.subheader('Molpher:')
st.markdown(
    """
    Molpher is a de novo drug design program which is systematically exploring chemical space using an iterative atom-based method known as molecular morphing [3], [4]. The main goal of this algorithm is to find a path consisting of intermediate structures between a given start molecule (Ms) and a given target molecule (Mt). The resulting set of intermediate structures (morphs) forms a virtual library that was generated using Molpher. Morphs combine the structural features of Ms and Mt in varying proportions. According to structure-activity relationship (SAR) principles, if Ms and Mt are both active to the same biological target, so should be some of their morphs. Molecular morphing is an iterative process, where for each next generation i+1 a new set of morphs is generated from the previous iteration i (see Figure 1). These morphs are generated by non-deterministic application of the morphing operators (see Figure 2). Morphing operators are simple structural changes (e.g, remove atom, add atom, link atom). 
    Link for publications: https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-6-7
"""
)

st.image(f'{current_directory}/recall_metrics/img/generators/Molpher.png', caption='Glucocorticoid_receptor')
